emails_csv = """
name,email,dept,number
ban,banjabateh7@gmail.com,IT,962782796835
ahmed,hamadaabusahyon@gmail.com,Sales,962788695523

"""

senders_csv = """
email,app_password
banjabateh7@gmail.com,unqa auty hqjn aeum
ban.mohammed41@gmail.com,xkfi mynx hsss sywb
"""

EVO_BASE_URL="http://localhost:8080"
EVO_INSTANCE_NAME='test'
AUTHENTICATION_API_KEY='justdoit'
